import { createStyles } from "antd-style";

export const useAssistantStyles = createStyles(({ token }) => ({
  root: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 320px",
    gap: token.marginLG,
    alignItems: "start",
    width: "100%",
  },
  main: { minWidth: 0 },
  prompt: {
    padding: `${token.padding}px ${token.paddingLG}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  label: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: `${token.paddingXXS}px ${token.paddingSM}px`,
    borderRadius: token.borderRadius,
    color: token.colorPrimary,
    background: token.colorFillSecondary,
    fontSize: token.fontSizeSM,
  },
  input: {
    width: "100%",
    border: 0,
    outline: 0,
    resize: "vertical",
    color: token.colorText,
    background: "transparent",
    fontSize: token.fontSize,
    lineHeight: 1.6,
  },
  action: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: `${token.paddingSM}px ${token.padding}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    color: token.colorTextSecondary,
    background: token.colorBgContainer,
    fontSize: token.fontSizeSM,
    cursor: "pointer",
  },
  suggestion: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: `${token.paddingSM}px ${token.padding}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadius,
    color: token.colorTextSecondary,
    background: token.colorBgContainer,
    fontSize: token.fontSizeSM,
    textAlign: "left",
    cursor: "pointer",
  },
  side: { display: "flex", flexDirection: "column", gap: token.margin },
  task: { padding: `${token.paddingSM}px 0`, borderBottom: `1px solid ${token.colorBorder}` },
  taskTitle: { display: "block", marginBottom: 3, fontSize: token.fontSizeSM },
  row: { display: "flex", alignItems: "center", gap: token.paddingSM },
  rowBetween: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: token.paddingSM,
  },
  column: { display: "flex", flexDirection: "column", gap: token.paddingSM },
  heading: { margin: 0, fontSize: 26, marginBottom: 4 },
  intro: { marginBottom: token.marginLG },
  promptRow: {
    display: "flex",
    alignItems: "center",
    gap: token.paddingSM,
    marginBottom: token.marginSM,
  },
  promptFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: token.paddingSM,
    marginTop: token.marginSM,
  },
  quickActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: token.marginSM,
    marginTop: token.marginLG,
  },
  suggestionsTitle: { margin: `${token.marginLG}px 0 ${token.marginSM}px` },
  suggestionArrow: { marginLeft: "auto", opacity: 0.5 },
  cardTitle: { margin: 0 },
  creditsRow: { marginBottom: token.marginXS },
  creditsHint: { marginTop: token.marginXS },
}));
