/**
 * Hidden SSR document. `html` is generated by marked in the route's server
 * component before it crosses the client boundary.
 */
export function SeoSnapshot({ title, html }: { title: string; html: string }) {
  return (
    <div className="sg-public-snapshot" hidden aria-hidden="true">
      <h1>{title}</h1>
      <div
        className="sg-markdown-content sg-public-markdown sg-public-markdown--seo"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
