/** Inline player chrome shared by generated artifacts and the Web iframe. */
export const SG_PRESENTATION_PLAYER_JS = String.raw`(function(){
"use strict";
var currentScript=document.currentScript;
var ui=!(currentScript&&currentScript.getAttribute("data-sg-player-ui")==="false");
var pages=[],current=0,ctrl=null,root=null,drawer=null,fill=null,label=null,prev=null,next=null;
function icon(name){var p={list:'<path d="M5 6h14M5 12h14M5 18h14"/><path d="M2 6h.01M2 12h.01M2 18h.01"/>',left:'<path d="m15 18-6-6 6-6"/>',right:'<path d="m9 18 6-6-6-6"/>',full:'<path d="M8 3H3v5M16 3h5v5M8 21H3v-5M21 16v5h-5"/>',download:'<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>',share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="m8 11 8-5M8 13l8 5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>'};return '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'+(p[name]||'')+'</svg>';}
function button(text,name){var b=document.createElement("button");b.type="button";b.setAttribute("data-sg-player-button","");b.setAttribute("aria-label",text);b.title=text;b.innerHTML=icon(name);return b;}
function title(p,i){return p.getAttribute("data-sg-title")||p.getAttribute("aria-label")||((p.querySelector("h1,h2,h3")||{}).textContent||"").trim()||("第 "+(i+1)+" 页");}
function sync(){if(!pages.length)return;current=Math.max(0,Math.min(pages.length-1,current));if(fill)fill.style.width=((current+1)/pages.length*100)+"%";if(label)label.textContent=String(current+1).padStart(2,"0")+" / "+String(pages.length).padStart(2,"0");if(prev)prev.disabled=current===0;if(next)next.disabled=current===pages.length-1;if(drawer)drawer.querySelectorAll("[data-sg-player-item]").forEach(function(b,i){b.setAttribute("aria-current",i===current?"page":"false");});}
function go(i){if(!pages.length)return;current=Math.max(0,Math.min(pages.length-1,Number(i)||0));if(ctrl&&ctrl.show)ctrl.show(current);else window.postMessage({sg:"goto",index:current},"*");sync();}
function mount(){if(document.querySelector("[data-sg-player-root]"))return;var s=document.createElement("style");s.setAttribute("data-sg-player-style","");s.textContent='[data-sg-player-root]{position:fixed;z-index:2147483000;left:0;right:0;bottom:0;pointer-events:none;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#d9e2e5}[data-sg-player-root] *{box-sizing:border-box}[data-sg-player-progress]{position:absolute;left:0;right:0;bottom:0;height:4px;background:rgba(255,255,255,.16);pointer-events:auto;cursor:pointer}[data-sg-player-fill]{display:block;height:100%;width:0;background:#7cf08a;transition:width 180ms ease}[data-sg-player-dock]{display:flex;align-items:center;gap:8px;margin:0 16px 18px auto;width:max-content;pointer-events:auto}[data-sg-player-button]{width:38px;height:38px;display:inline-flex;align-items:center;justify-content:center;border:1px solid rgba(190,220,208,.22);border-radius:0;background:rgba(9,16,14,.86);color:rgba(232,244,238,.86);cursor:pointer}[data-sg-player-button]:hover{border-color:#63e6be;color:#63e6be}[data-sg-player-button][disabled]{opacity:.3;cursor:default}[data-sg-player-label]{min-width:48px;text-align:center;color:rgba(240,248,244,.9);font-size:12px;font-variant-numeric:tabular-nums}[data-sg-player-drawer]{position:absolute;right:16px;bottom:76px;width:min(390px,calc(100vw - 32px));max-height:min(72vh,620px);overflow:auto;padding:14px;background:rgba(7,16,16,.96);border:1px solid rgba(114,140,143,.42);box-shadow:0 20px 60px rgba(0,0,0,.45);pointer-events:auto}[data-sg-player-drawer][hidden]{display:none}[data-sg-player-head]{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;font-size:15px;font-weight:700}[data-sg-player-list]{display:grid;gap:8px}[data-sg-player-item]{display:flex;gap:10px;align-items:flex-start;width:100%;padding:10px 11px;border:1px solid rgba(114,140,143,.28);background:transparent;color:#afbec0;text-align:left;cursor:pointer;font:inherit}[data-sg-player-item]:hover,[data-sg-player-item][aria-current="page"]{border-color:#63e6be;color:#efffff;background:rgba(18,48,43,.5)}[data-sg-player-item-no]{font-size:11px;opacity:.65;letter-spacing:.08em}[data-sg-player-close]{border:0;background:transparent;color:#a8b7ba;font-size:20px;cursor:pointer}';document.head.appendChild(s);
root=document.createElement("div");root.setAttribute("data-sg-player-root","");var bar=document.createElement("div");bar.setAttribute("data-sg-player-progress","");fill=document.createElement("span");fill.setAttribute("data-sg-player-fill","");bar.appendChild(fill);bar.onclick=function(e){var r=bar.getBoundingClientRect();go(Math.round(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*(pages.length-1)));};root.appendChild(bar);
drawer=document.createElement("aside");drawer.setAttribute("data-sg-player-drawer","");drawer.hidden=true;var h=document.createElement("div");h.setAttribute("data-sg-player-head","");h.innerHTML="<span>演示目录</span>";var close=button("关闭目录","close");close.setAttribute("data-sg-player-close","");close.onclick=function(){drawer.hidden=true;};h.appendChild(close);drawer.appendChild(h);var list=document.createElement("nav");list.setAttribute("data-sg-player-list","");pages.forEach(function(p,i){var b=document.createElement("button");b.type="button";b.setAttribute("data-sg-player-item","");b.setAttribute("aria-current",i===0?"page":"false");b.textContent=String(i+1).padStart(2,"0")+"  "+title(p,i);b.onclick=function(){go(i);drawer.hidden=true;};list.appendChild(b);});drawer.appendChild(list);root.appendChild(drawer);
var dock=document.createElement("footer");dock.setAttribute("data-sg-player-dock","");var menu=button("打开演示目录","list");menu.onclick=function(){drawer.hidden=!drawer.hidden;};prev=button("上一页","left");prev.onclick=function(){go(current-1);};label=document.createElement("span");label.setAttribute("data-sg-player-label","");next=button("下一页","right");next.onclick=function(){go(current+1);};var full=button("全屏播放","full");full.onclick=function(){if(document.fullscreenElement)document.exitFullscreen&&document.exitFullscreen();else document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen();};var share=button("分享演示","share");share.onclick=function(){var url=location.href;if(navigator.share)navigator.share({title:document.title,url:url}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(url).then(function(){share.title="链接已复制";setTimeout(function(){share.title="分享演示";},1200);});};var downloadLink=document.querySelector(".sg-publish-download[href]");var download=downloadLink?button("下载演示","download"):null;if(download){download.onclick=function(){location.href=downloadLink.href;};}dock.append(menu,prev,label,next,full);if(download)dock.appendChild(download);dock.appendChild(share);root.appendChild(dock);document.body.appendChild(root);sync();}
function boot(){pages=Array.prototype.slice.call(document.querySelectorAll("[data-sg-page]"));if(!pages.length)return;if(window.__sgPlatformPresentation&&window.__sgPlatformPresentation.show)ctrl=window.__sgPlatformPresentation;else if(window.SG&&window.SG.presentation){ctrl=window.SG.presentation({mode:"slide",keyboard:true,touch:true});window.__sgPlatformPresentation=ctrl;}if(ui)mount();window.addEventListener("message",function(e){var d=e.data;if(d&&d.sg==="page"&&typeof d.index==="number"){current=d.index;sync();}});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&drawer&&!drawer.hidden){drawer.hidden=true;return;}if(e.key==="ArrowRight"||e.key==="PageDown"||e.key===" "){e.preventDefault();go(current+1);}else if(e.key==="ArrowLeft"||e.key==="PageUp"){e.preventDefault();go(current-1);}else if(e.key==="Home"){e.preventDefault();go(0);}else if(e.key==="End"){e.preventDefault();go(pages.length-1);}});if(ui)document.querySelectorAll("#sg-progress,#sg-page-no,body > .sg-nav").forEach(function(e){e.style.display="none";});sync();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();`;
