import { createStyles } from "antd-style";

/** Home-only layout styles. Keep these local so page changes cannot leak into other routes. */
export const useHomeStyles = createStyles(({ token }) => ({
  home: { width: "100%", maxWidth: "none", margin: 0, color: token.colorText },
  hero: {
    position: "relative",
    minHeight: 276,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "40px 56px 44px",
    overflow: "hidden",
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: `url('/reference/home-hero-background-v3.webp') center / cover no-repeat`,
  },
  heroTitle: {
    position: "relative",
    zIndex: 1,
    width: "70%",
    margin: "0 0 24px",
    color: token.colorText,
    fontSize: 38,
    fontWeight: 700,
    lineHeight: 1.2,
    textAlign: "center",
  },
  heroCompose: {
    position: "relative",
    zIndex: 1,
    width: "min(704px, 62%)",
    minHeight: 78,
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginLeft: "7%",
    padding: "11px 12px 11px 24px",
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
    boxShadow: token.boxShadowSecondary,
  },
  heroInput: {
    flex: 1,
    minWidth: 0,
    border: 0,
    outline: 0,
    color: token.colorText,
    background: "transparent",
    fontSize: token.fontSize,
  },
  heroSubmit: {
    width: 44,
    height: 44,
    flex: "none",
    display: "grid",
    placeItems: "center",
    border: 0,
    borderRadius: "50%",
    color: token.colorWhite,
    background: token.colorPrimary,
    cursor: "pointer",
  },
  quickCreate: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 12,
    margin: "14px 0",
  },
  quickItem: {
    minWidth: 0,
    minHeight: 96,
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "15px 16px",
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadius,
    color: token.colorText,
    background: token.colorBgContainer,
    textAlign: "left",
    cursor: "pointer",
  },
  quickIcon: {
    width: 58,
    height: 58,
    flex: "none",
    display: "grid",
    placeItems: "center",
    borderRadius: token.borderRadius,
    color: token.colorWhite,
    background: token.colorPrimary,
  },
  quickIconBlue: { background: token.colorInfo },
  quickIconGreen: { background: token.colorSuccess },
  quickIconViolet: { background: token.colorInfo },
  quickIconCyan: { background: token.colorInfo },
  quickCopy: { minWidth: 0, display: "flex", flex: 1, flexDirection: "column" },
  quickCopyHint: { marginTop: 3, color: token.colorTextTertiary },
  homeColumns: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 14,
    alignItems: "stretch",
  },
  panel: {
    minWidth: 0,
    minHeight: 436,
    overflow: "hidden",
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadius,
    background: token.colorBgContainer,
  },
  sectionHead: {
    minHeight: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
  },
  sectionHeadTitle: { margin: 0, fontSize: token.fontSize },
  sectionHeadAction: {
    border: 0,
    color: token.colorTextTertiary,
    background: "transparent",
    cursor: "pointer",
  },
  runningBody: { padding: "0 16px 16px" },
  runningCard: {
    width: "100%",
    minHeight: 105,
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: 16,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadius,
    color: token.colorText,
    background: token.colorBgElevated,
    textAlign: "left",
    cursor: "pointer",
  },
  runningIcon: {
    width: 50,
    height: 50,
    flex: "none",
    display: "grid",
    placeItems: "center",
    borderRadius: token.borderRadius,
    color: token.colorInfo,
    background: token.colorFillSecondary,
  },
  runningInfo: { minWidth: 0, display: "flex", flex: 1, flexDirection: "column" },
  progressLine: {
    height: 5,
    overflow: "hidden",
    margin: "10px 0 7px",
    borderRadius: 3,
    background: token.colorFillSecondary,
  },
  progressFill: {
    display: "block",
    height: "100%",
    borderRadius: "inherit",
    background: token.colorPrimary,
  },
  runningProgress: {
    width: 92,
    flex: "none",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  runningProgressValue: { color: token.colorPrimary, fontSize: token.fontSize, fontWeight: 600 },
  runningProgressHint: { color: token.colorTextTertiary, whiteSpace: "nowrap" },
  templateSection: { padding: 16, borderTop: `1px solid ${token.colorBorderSecondary}` },
  templateTitle: { margin: "0 0 13px", fontSize: token.fontSize },
  templateGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 10 },
  templateCard: {
    minWidth: 0,
    overflow: "hidden",
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadius,
    background: token.colorBgElevated,
  },
  templateImage: { width: "100%", height: 100, display: "block", objectFit: "cover" },
  templateBody: { padding: 10 },
  templateDescription: {
    display: "block",
    margin: "3px 0 9px",
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  templateButton: {
    width: "100%",
    height: 28,
    border: `1px solid ${token.colorPrimary}`,
    borderRadius: token.borderRadiusSM,
    color: token.colorPrimary,
    background: "transparent",
    cursor: "pointer",
  },
  recentContent: { padding: "0 18px" },
  recentTable: { width: "100%", borderCollapse: "collapse", tableLayout: "fixed" },
  recentCell: {
    height: 53,
    overflow: "hidden",
    padding: "0 8px",
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
    color: token.colorTextSecondary,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  recentNameCell: { display: "flex", alignItems: "center", gap: 10, color: token.colorText },
  fileIcon: {
    width: 29,
    height: 29,
    flex: "none",
    display: "grid",
    placeItems: "center",
    borderRadius: token.borderRadiusSM,
    color: token.colorWhite,
    background: token.colorPrimary,
  },
  fileIconPresentation: { background: token.colorWarning },
  fileIconPdf: { background: token.colorError },
  fileIconKnowledge: { background: token.colorInfo },
  recentEmpty: {
    width: "100%",
    minHeight: 110,
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: 16,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadius,
    color: token.colorText,
    background: token.colorBgElevated,
    textAlign: "left",
    cursor: "pointer",
  },
  recentEmptyCopy: { display: "flex", flex: 1, flexDirection: "column" },
  viewAll: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    margin: "15px 20px 0 auto",
    border: 0,
    color: token.colorTextSecondary,
    background: "transparent",
    cursor: "pointer",
  },
}));
