import { createStyles } from "antd-style";

export const useDocumentTreeStyles = createStyles(({ token, responsive }) => ({
  workspace: responsive({
    xs: {
      display: "grid",
      minWidth: 0,
      gridTemplateColumns: "1fr",
      gap: token.marginLG,
      alignItems: "start",
    },
    md: {
      display: "grid",
      minWidth: 0,
      gridTemplateColumns: "200px minmax(0, 1fr)",
      gap: token.marginLG,
      alignItems: "start",
    },
    lg: {
      display: "grid",
      minWidth: 0,
      gridTemplateColumns: "220px minmax(0, 1fr)",
      gap: token.marginLG,
      alignItems: "start",
    },
  }),
  panel: responsive({
    xs: {
      position: "static",
      minWidth: 0,
      maxHeight: 280,
      overflowY: "auto",
      padding: token.paddingSM,
      border: `1px solid ${token.colorBorder}`,
      borderRadius: token.borderRadiusLG,
      background: token.colorBgContainer,
    },
    md: {
      position: "sticky",
      top: 14,
      minWidth: 0,
      maxHeight: "calc(100vh - 190px)",
      overflowY: "auto",
      padding: token.paddingSM,
      border: `1px solid ${token.colorBorder}`,
      borderRadius: token.borderRadiusLG,
      background: token.colorBgContainer,
    },
  }),
  heading: {
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: `0 ${token.paddingXS}px ${token.paddingXS}px ${token.paddingSM}px`,
    color: token.colorText,
    fontSize: token.fontSizeSM,
  },
  headingActions: { display: "flex", alignItems: "center", gap: 2 },
  content: { display: "block" },
  contentClosed: responsive({ xs: { display: "none" }, md: { display: "block" } }),
  iconButton: {
    display: "grid",
    width: 26,
    height: 26,
    flex: "none",
    placeItems: "center",
    padding: 0,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextTertiary,
    background: "transparent",
    cursor: "pointer",
  },
  systemViews: { display: "grid", gap: 2 },
  systemView: {
    display: "flex",
    width: "100%",
    height: 32,
    alignItems: "center",
    gap: token.paddingXS,
    padding: `0 ${token.paddingSM}px`,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextTertiary,
    background: "transparent",
    fontSize: token.fontSizeSM,
    textAlign: "left",
    cursor: "pointer",
  },
  systemViewActive: {
    color: token.colorText,
    background: `color-mix(in srgb, ${token.colorPrimary} 14%, transparent)`,
  },
  divider: {
    height: 1,
    margin: `${token.marginSM}px ${token.paddingXS}px`,
    background: token.colorBorder,
  },
  subheading: {
    padding: `2px ${token.paddingSM}px 7px`,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  treeRow: {
    minWidth: 0,
    height: 32,
    display: "flex",
    alignItems: "center",
    paddingRight: 3,
    borderRadius: token.borderRadius,
    background: "transparent",
  },
  treeRowActive: {
    background: token.colorBgElevated,
    boxShadow: `inset 2px 0 0 ${token.colorPrimary}`,
  },
  treeLabel: {
    display: "flex",
    minWidth: 0,
    height: "100%",
    flex: 1,
    alignItems: "center",
    gap: 7,
    overflow: "hidden",
    padding: `0 ${token.paddingXS}px`,
    border: 0,
    color: token.colorTextSecondary,
    background: "transparent",
    fontSize: token.fontSizeSM,
    textAlign: "left",
    cursor: "pointer",
  },
  treeMore: {
    display: "grid",
    width: 26,
    height: 26,
    flex: "none",
    placeItems: "center",
    padding: 0,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextTertiary,
    background: "transparent",
    cursor: "pointer",
  },
  treeMoreHidden: { opacity: 0 },
  main: { minWidth: 0 },
  location: {
    minHeight: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: token.margin,
    marginBottom: token.marginSM,
    padding: `0 ${token.paddingXXS}px ${token.paddingSM}px`,
    borderBottom: `1px solid ${token.colorBorder}`,
  },
  locationCopy: { display: "flex", minWidth: 0, alignItems: "baseline", gap: token.paddingXS },
  locationLabel: { flex: "none", color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  locationTitle: {
    overflow: "hidden",
    color: token.colorText,
    fontSize: token.fontSizeSM,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  collapse: responsive({
    xs: {
      display: "grid",
      width: 26,
      height: 26,
      placeItems: "center",
      padding: 0,
      border: 0,
      borderRadius: token.borderRadius,
      color: token.colorTextTertiary,
      background: "transparent",
      cursor: "pointer",
    },
    md: { display: "none" },
  }),
}));
