import { createStyles } from "antd-style";

export const useDocumentCardStyles = createStyles(({ token, responsive }) => ({
  grid: responsive({
    xs: { display: "grid", gridTemplateColumns: "1fr", gap: token.padding },
    md: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: token.padding },
    lg: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: token.padding },
  }),
  card: {
    display: "flex",
    minWidth: 0,
    minHeight: 202,
    flexDirection: "column",
    padding: token.padding,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
    cursor: "pointer",
    outline: "none",
    transition: "border-color 150ms ease, background 150ms ease, transform 150ms ease",
  },
  cardHead: { display: "flex", alignItems: "center", gap: 9 },
  cardType: { color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  cardBody: { minWidth: 0, marginTop: token.margin },
  cardTitle: {
    display: "block",
    width: "100%",
    margin: 0,
    overflow: "hidden",
    padding: 0,
    border: 0,
    color: token.colorText,
    background: "transparent",
    fontSize: token.fontSize,
    fontWeight: 650,
    lineHeight: 1.45,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  cardDescription: {
    display: "-webkit-box",
    overflow: "hidden",
    margin: `${token.marginXS}px 0 0`,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    lineHeight: 1.5,
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: token.marginXS,
    marginTop: "auto",
    paddingTop: token.padding,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  cardFoot: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: token.marginXS,
    marginTop: token.marginSM,
    paddingTop: token.paddingSM,
    borderTop: `1px solid ${token.colorBorder}`,
  },
  relations: {
    minWidth: 0,
    overflow: "hidden",
    flex: 1,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  actions: { display: "flex", flex: "none", alignItems: "center", gap: token.marginXXS },
  action: { color: token.colorTextSecondary },
  actionAi: { color: token.colorPrimary },
}));
