import { createStyles } from "antd-style";

export const useDocumentsStyles = createStyles(({ token }) => ({
  root: { width: "100%" },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: token.margin,
    marginBottom: token.marginLG,
  },
  stat: {
    display: "flex",
    flexDirection: "column",
    gap: token.marginXXS,
    padding: `${token.paddingSM}px ${token.padding}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  statLabel: { color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  statValue: { color: token.colorWarning, fontSize: 26, fontWeight: 750, lineHeight: 1.1 },
  recentSection: { marginTop: token.marginLG },
  recentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: token.margin,
  },
  recentCard: {
    display: "flex",
    alignItems: "center",
    gap: token.margin,
    minWidth: 0,
    padding: `${token.paddingSM}px ${token.padding}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
    cursor: "pointer",
    textAlign: "left",
  },
  recentCopy: { minWidth: 0, display: "flex", flexDirection: "column", gap: token.marginXXS },
  recentTitle: {
    overflow: "hidden",
    color: token.colorText,
    fontSize: token.fontSize,
    fontWeight: 600,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  recentMeta: {
    display: "flex",
    alignItems: "center",
    gap: token.paddingXS,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  description: {
    display: "block",
    overflow: "hidden",
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", minWidth: 880, borderCollapse: "collapse" },
  tableHeader: {
    height: 40,
    padding: `0 ${token.padding}px`,
    borderBottom: `1px solid ${token.colorBorder}`,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    fontWeight: 500,
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  tableCell: {
    height: 64,
    padding: `${token.paddingSM}px ${token.padding}px`,
    borderBottom: `1px solid ${token.colorBorder}`,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
    verticalAlign: "middle",
  },
  tableMenuHeader: { width: 150, textAlign: "right" },
  tableMenuCell: { textAlign: "right" },
  actions: { display: "inline-flex", alignItems: "center", justifyContent: "flex-end", gap: 2 },
  actionButton: { color: token.colorTextTertiary, padding: `0 ${token.paddingXS}px`, height: 28 },
  actionButtonAi: { color: token.colorPrimary },
  moveHint: {
    margin: `0 0 ${token.marginSM}px`,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  moveTree: {
    maxHeight: "min(420px, 55vh)",
    overflowY: "auto",
    padding: token.paddingXS,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgLayout,
  },
  moveFolder: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    width: "100%",
    minHeight: 40,
    padding: `${token.paddingSM}px ${token.padding}px`,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextSecondary,
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  moveFolderSelected: {
    color: token.colorPrimary,
    background: `color-mix(in srgb, ${token.colorPrimary} 14%, transparent)`,
  },
  moveFolderName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  moveFolderCheck: { flex: "none", marginLeft: "auto" },
  moveFooter: { display: "flex", justifyContent: "flex-end", gap: token.paddingSM },
}));
