import { createStyles } from "antd-style";

export const useAssetsStyles = createStyles(({ token }) => ({
  root: { width: "100%" },
  body: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 264px",
    gap: token.marginLG,
    alignItems: "start",
  },
  list: { minWidth: 0 },
  head: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: token.marginLG,
    marginBottom: token.margin,
  },
  headActions: { display: "flex", alignItems: "center", gap: token.paddingSM, flex: "none" },
  subtitle: { margin: 0, color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  headButton: {
    height: 34,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: `0 ${token.padding}px`,
    borderRadius: token.borderRadius,
    color: token.colorPrimary,
    background: "transparent",
  },
  typeTabs: { marginBottom: token.margin },
  toolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: token.paddingSM,
    marginBottom: token.marginSM,
  },
  search: { width: 260 },
  select: { width: 118 },
  batch: { display: "flex", alignItems: "center", gap: token.paddingSM, marginLeft: "auto" },
  tableWrap: {
    overflowX: "auto",
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  table: { width: "100%", minWidth: 880, borderCollapse: "collapse", tableLayout: "fixed" },
  tableHeader: {
    height: 40,
    padding: `0 ${token.paddingSM}px`,
    borderBottom: `1px solid ${token.colorBorder}`,
    color: token.colorTextTertiary,
    background: token.colorBgElevated,
    fontSize: token.fontSizeSM,
    fontWeight: 500,
    textAlign: "left",
  },
  tableCell: {
    height: 60,
    overflow: "hidden",
    padding: `${token.paddingSM}px`,
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  row: { cursor: "pointer" },
  assetName: { display: "flex", alignItems: "center", gap: token.marginSM, minWidth: 0 },
  assetNameCopy: { minWidth: 0, display: "flex", flexDirection: "column", gap: 3 },
  assetTitle: {
    display: "block",
    overflow: "hidden",
    color: token.colorText,
    fontSize: token.fontSize,
    fontWeight: 600,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  assetTags: { display: "flex", gap: 4, overflow: "hidden" },
  assetTag: {
    flex: "none",
    padding: "0 7px",
    borderRadius: token.borderRadiusSM,
    color: token.colorTextTertiary,
    background: token.colorFillSecondary,
    fontSize: token.fontSizeSM,
    lineHeight: "18px",
  },
  assetIcon: {
    width: 32,
    height: 32,
    flex: "none",
    display: "grid",
    placeItems: "center",
    borderRadius: token.borderRadius,
    color: token.colorPrimary,
    background: token.colorFillSecondary,
  },
  ownerStack: { display: "inline-flex", alignItems: "center", minWidth: 28, paddingLeft: 2 },
  ownerAvatar: {
    width: 28,
    height: 28,
    display: "grid",
    flex: "none",
    placeItems: "center",
    border: `2px solid ${token.colorBgContainer}`,
    borderRadius: "50%",
    color: token.colorWhite,
    background: token.colorInfo,
    fontSize: token.fontSizeSM,
    fontWeight: 600,
    lineHeight: 1,
    textTransform: "uppercase",
  },
  check: { display: "inline-flex", cursor: "pointer" },
  menu: {
    display: "flex",
    flexDirection: "column",
    padding: 5,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgElevated,
    boxShadow: token.boxShadowSecondary,
  },
  status: { display: "inline-flex", alignItems: "center", gap: 6, whiteSpace: "nowrap" },
  statusDot: { width: 7, height: 7, flex: "none", borderRadius: "50%" },
  visibility: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    maxWidth: "100%",
    overflow: "hidden",
    fontSize: token.fontSizeSM,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  more: {
    width: 28,
    height: 28,
    display: "grid",
    placeItems: "center",
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextTertiary,
    background: "transparent",
    cursor: "pointer",
  },
  pager: {
    display: "flex",
    alignItems: "center",
    gap: token.paddingSM,
    padding: `${token.paddingSM}px ${token.paddingXXS}px 0`,
  },
  pagerPages: { display: "flex", alignItems: "center", gap: 4, margin: "0 auto" },
  pagerTotal: { color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  pageButton: {
    minWidth: 28,
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: `0 ${token.paddingXS}px`,
    border: `1px solid transparent`,
    borderRadius: token.borderRadius,
    color: token.colorTextSecondary,
    background: "transparent",
    fontSize: token.fontSizeSM,
    cursor: "pointer",
  },
  pageButtonActive: { color: token.colorWhite, background: token.colorPrimary },
  pageEllipsis: { padding: "0 3px", color: token.colorTextTertiary },
  pagerSize: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  pagerSizeSelect: { width: 92 },
  side: {
    display: "flex",
    flexDirection: "column",
    gap: token.margin,
    position: "sticky",
    top: 14,
    minWidth: 0,
  },
  sideCard: {
    padding: `${token.padding}px ${token.padding}px ${token.paddingLG}px`,
    border: `1px solid ${token.colorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  sideTitle: { margin: `0 0 ${token.marginSM}px`, fontSize: token.fontSize },
  quickList: { display: "flex", flexDirection: "column", gap: 2 },
  quickItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minHeight: 36,
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorTextSecondary,
    background: "transparent",
    fontSize: token.fontSizeSM,
    textAlign: "left",
    cursor: "pointer",
  },
  quickItemActive: { color: token.colorPrimary, background: token.colorFillSecondary },
  quickIcon: {
    width: 26,
    height: 26,
    flex: "none",
    display: "grid",
    placeItems: "center",
    borderRadius: token.borderRadius,
    color: token.colorPrimary,
    background: token.colorFillSecondary,
  },
  quickCount: { marginLeft: "auto", color: token.colorTextTertiary, fontSize: token.fontSizeSM },
  storageNum: { marginTop: token.marginSM, color: token.colorText, fontSize: 17, fontWeight: 650 },
  storageBar: { margin: `${token.marginSM}px 0 ${token.marginXS}px` },
  sideRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: token.paddingSM,
  },
  recentList: { display: "flex", flexDirection: "column" },
  recentItem: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    width: "100%",
    padding: `${token.paddingXS}px 0`,
    border: 0,
    color: token.colorTextSecondary,
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  },
  recentName: {
    minWidth: 0,
    overflow: "hidden",
    fontSize: token.fontSizeSM,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  recentTime: {
    flex: "none",
    marginLeft: "auto",
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  tagCloud: { display: "flex", flexWrap: "wrap", gap: 6 },
  cloudTag: {
    padding: `3px ${token.paddingSM}px`,
    border: 0,
    borderRadius: token.borderRadius,
    color: token.colorPrimary,
    background: token.colorFillSecondary,
    fontSize: token.fontSizeSM,
    cursor: "pointer",
  },
}));
